### PR TITLE
Add ottojiang (Jian Jiang) as contributor 

### PR DESCRIPTION
**Pull request by ottojiang**

### CODE REVIEW

**Comment by ottojiang** [comment]
@michaelficarra please help

**Review by michaelficarra — APPROVED** [review]

**Comment by ottojiang** [comment]
@michaelficarra  can you help to merge, thanks.

**Comment by michaelficarra** [comment]
@ottojiang you either need to commit as mail.com or add gmail.com instead.

**Comment by ottojiang** [comment]
@michaelficarra  fixed

**Review by michaelficarra — APPROVED** [review]

**Pull request merged**
